### PR TITLE
Fix fields_under_root and fields

### PR DESCRIPTION
**Pull request by max252**
According to the instructions

### CODE REVIEW

**Comment by corey-hammerton** [comment]
@max252 Please look into the build errors before this PR can be merged.

**Comment by corey-hammerton** [comment]
@max252 Please re-sync from Master to confirm that Travis-CI builds successfully.

**Comment by sasubillis** [comment]
> @max252 Please re-sync from Master to confirm that Travis-CI builds successfully.

@max252 Could you please resync from master and see if that helps to succeed with build process?

**Comment by corey-hammerton** [comment]
Closing in favour of #40

**Pull request closed without merging**
